export type UltimateWeapon = Readonly<{
  upgrades: Readonly<{
    [upgrade: string]: Readonly<{
      values: Readonly<Readonly<{ value: number; cost: number }>[]>;
      lab?: Readonly<{ growth: number; max: number }>;
      perk?: Readonly<(value: number) => number>;
      formatValue: (value: number) => string;
    }>;
  }>;
}>;
export type UltimateWeapons = Readonly<{
  [UltimateWeapon: string]: UltimateWeapon;
}>;

const damage = (value: number) => `${value.toFixed(0)}%`;
const damageTimes = (value: number) => `${value.toFixed(0)}x`;
const slow = (value: number) => `${value.toFixed(0)}%`;
const chance = (value: number) => `${value.toFixed(2)}%`;
const quantity = (value: number) => `${value.toFixed(0)}`;
const seconds = (value: number) => `${value.toFixed(0)}s`;
const size = (value: number) => `${value.toFixed(0)}m`;
const bonus = (value: number) => `${value.toFixed(2)}x`;

const DEATH_WAVE: UltimateWeapon = Object.freeze({
  upgrades: Object.freeze({
    'Damage %': Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 150, cost: 0 }),
        Object.freeze({ value: 177, cost: 5 }),
        Object.freeze({ value: 205, cost: 11 }),
        Object.freeze({ value: 233, cost: 17 }),
        Object.freeze({ value: 261, cost: 23 }),
        Object.freeze({ value: 290, cost: 29 }),
        Object.freeze({ value: 319, cost: 35 }),
        Object.freeze({ value: 348, cost: 41 }),
        Object.freeze({ value: 377, cost: 47 }),
        Object.freeze({ value: 406, cost: 53 }),
        Object.freeze({ value: 436, cost: 61 }),
        Object.freeze({ value: 465, cost: 71 }),
        Object.freeze({ value: 495, cost: 84 }),
        Object.freeze({ value: 524, cost: 100 }),
        Object.freeze({ value: 554, cost: 120 }),
        Object.freeze({ value: 584, cost: 144 }),
        Object.freeze({ value: 614, cost: 174 }),
        Object.freeze({ value: 644, cost: 210 }),
        Object.freeze({ value: 674, cost: 254 }),
        Object.freeze({ value: 704, cost: 308 }),
        Object.freeze({ value: 735, cost: 374 }),
        Object.freeze({ value: 765, cost: 452 }),
        Object.freeze({ value: 795, cost: 558 }),
        Object.freeze({ value: 826, cost: 694 }),
        Object.freeze({ value: 856, cost: 880 }),
        Object.freeze({ value: 887, cost: 1126 }),
        Object.freeze({ value: 917, cost: 1436 }),
        Object.freeze({ value: 948, cost: 1813 }),
        Object.freeze({ value: 979, cost: 2269 }),
        Object.freeze({ value: 1010, cost: 2800 }),
        Object.freeze({ value: 1040, cost: 4081 }),
      ]),
      formatValue: damage,
    }),
    Quantity: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 1, cost: 0 }),
        Object.freeze({ value: 2, cost: 200 }),
        Object.freeze({ value: 3, cost: 500 }),
        Object.freeze({ value: 4, cost: 850 }),
        Object.freeze({ value: 5, cost: 1400 }),
      ]),
      perk: (value: number) => value + 1,
      formatValue: quantity,
    }),
    Cooldown: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 300, cost: 0 }),
        Object.freeze({ value: 290, cost: 8 }),
        Object.freeze({ value: 280, cost: 24 }),
        Object.freeze({ value: 270, cost: 40 }),
        Object.freeze({ value: 260, cost: 56 }),
        Object.freeze({ value: 250, cost: 72 }),
        Object.freeze({ value: 240, cost: 88 }),
        Object.freeze({ value: 230, cost: 104 }),
        Object.freeze({ value: 220, cost: 120 }),
        Object.freeze({ value: 210, cost: 136 }),
        Object.freeze({ value: 200, cost: 152 }),
        Object.freeze({ value: 190, cost: 168 }),
        Object.freeze({ value: 180, cost: 184 }),
        Object.freeze({ value: 170, cost: 200 }),
        Object.freeze({ value: 160, cost: 216 }),
        Object.freeze({ value: 150, cost: 232 }),
        Object.freeze({ value: 140, cost: 248 }),
        Object.freeze({ value: 130, cost: 264 }),
        Object.freeze({ value: 120, cost: 280 }),
        Object.freeze({ value: 110, cost: 346 }),
        Object.freeze({ value: 100, cost: 512 }),
      ]),
      formatValue: seconds,
    }),
  }),
});

const BLACK_HOLE: UltimateWeapon = Object.freeze({
  upgrades: Object.freeze({
    Size: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 30, cost: 0 }),
        Object.freeze({ value: 32, cost: 5 }),
        Object.freeze({ value: 34, cost: 12 }),
        Object.freeze({ value: 36, cost: 19 }),
        Object.freeze({ value: 38, cost: 26 }),
        Object.freeze({ value: 40, cost: 34 }),
        Object.freeze({ value: 42, cost: 43 }),
        Object.freeze({ value: 44, cost: 53 }),
        Object.freeze({ value: 46, cost: 64 }),
        Object.freeze({ value: 48, cost: 76 }),
        Object.freeze({ value: 50, cost: 89 }),
        Object.freeze({ value: 52, cost: 103 }),
        Object.freeze({ value: 54, cost: 118 }),
        Object.freeze({ value: 56, cost: 134 }),
        Object.freeze({ value: 58, cost: 151 }),
        Object.freeze({ value: 60, cost: 169 }),
        Object.freeze({ value: 62, cost: 189 }),
        Object.freeze({ value: 64, cost: 211 }),
        Object.freeze({ value: 66, cost: 236 }),
        Object.freeze({ value: 68, cost: 264 }),
        Object.freeze({ value: 70, cost: 295 }),
      ]),
      formatValue: size,
    }),
    Duration: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 15, cost: 0 }),
        Object.freeze({ value: 16, cost: 5 }),
        Object.freeze({ value: 17, cost: 14 }),
        Object.freeze({ value: 18, cost: 23 }),
        Object.freeze({ value: 19, cost: 32 }),
        Object.freeze({ value: 20, cost: 41 }),
        Object.freeze({ value: 21, cost: 50 }),
        Object.freeze({ value: 22, cost: 59 }),
        Object.freeze({ value: 23, cost: 68 }),
        Object.freeze({ value: 24, cost: 77 }),
        Object.freeze({ value: 25, cost: 86 }),
        Object.freeze({ value: 26, cost: 95 }),
        Object.freeze({ value: 27, cost: 104 }),
        Object.freeze({ value: 28, cost: 113 }),
        Object.freeze({ value: 29, cost: 122 }),
        Object.freeze({ value: 30, cost: 131 }),
      ]),
      perk: (value: number) => value + 12,
      formatValue: seconds,
    }),
    Cooldown: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 200, cost: 0 }),
        Object.freeze({ value: 190, cost: 10 }),
        Object.freeze({ value: 180, cost: 28 }),
        Object.freeze({ value: 170, cost: 46 }),
        Object.freeze({ value: 160, cost: 64 }),
        Object.freeze({ value: 150, cost: 82 }),
        Object.freeze({ value: 140, cost: 100 }),
        Object.freeze({ value: 130, cost: 118 }),
        Object.freeze({ value: 120, cost: 136 }),
        Object.freeze({ value: 110, cost: 154 }),
        Object.freeze({ value: 100, cost: 172 }),
        Object.freeze({ value: 90, cost: 190 }),
        Object.freeze({ value: 80, cost: 208 }),
        Object.freeze({ value: 70, cost: 226 }),
        Object.freeze({ value: 60, cost: 244 }),
        Object.freeze({ value: 50, cost: 262 }),
      ]),
      formatValue: seconds,
    }),
  }),
});

const GOLDEN_TOWER: UltimateWeapon = Object.freeze({
  upgrades: Object.freeze({
    Bonus: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 5.0, cost: 0 }),
        Object.freeze({ value: 5.8, cost: 5 }),
        Object.freeze({ value: 6.6, cost: 13 }),
        Object.freeze({ value: 7.4, cost: 22 }),
        Object.freeze({ value: 8.2, cost: 32 }),
        Object.freeze({ value: 9.0, cost: 43 }),
        Object.freeze({ value: 9.8, cost: 55 }),
        Object.freeze({ value: 10.6, cost: 68 }),
        Object.freeze({ value: 11.4, cost: 82 }),
        Object.freeze({ value: 12.2, cost: 98 }),
        Object.freeze({ value: 13.0, cost: 116 }),
        Object.freeze({ value: 13.8, cost: 138 }),
        Object.freeze({ value: 14.6, cost: 162 }),
        Object.freeze({ value: 15.4, cost: 250 }),
        Object.freeze({ value: 16.2, cost: 350 }),
        Object.freeze({ value: 17.0, cost: 500 }),
      ]),
      lab: Object.freeze({ growth: 0.15, max: 25 }),
      perk: (value: number) => value * 1.5,
      formatValue: bonus,
    }),
    Duration: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 15, cost: 0 }),
        Object.freeze({ value: 16, cost: 5 }),
        Object.freeze({ value: 17, cost: 14 }),
        Object.freeze({ value: 18, cost: 23 }),
        Object.freeze({ value: 19, cost: 32 }),
        Object.freeze({ value: 20, cost: 41 }),
        Object.freeze({ value: 21, cost: 50 }),
        Object.freeze({ value: 22, cost: 59 }),
        Object.freeze({ value: 23, cost: 68 }),
        Object.freeze({ value: 24, cost: 77 }),
        Object.freeze({ value: 25, cost: 87 }),
        Object.freeze({ value: 26, cost: 98 }),
        Object.freeze({ value: 27, cost: 110 }),
        Object.freeze({ value: 28, cost: 123 }),
        Object.freeze({ value: 29, cost: 137 }),
        Object.freeze({ value: 30, cost: 152 }),
        Object.freeze({ value: 31, cost: 168 }),
        Object.freeze({ value: 32, cost: 185 }),
        Object.freeze({ value: 33, cost: 203 }),
        Object.freeze({ value: 34, cost: 222 }),
        Object.freeze({ value: 35, cost: 242 }),
        Object.freeze({ value: 36, cost: 263 }),
        Object.freeze({ value: 37, cost: 285 }),
        Object.freeze({ value: 38, cost: 308 }),
        Object.freeze({ value: 39, cost: 332 }),
        Object.freeze({ value: 40, cost: 356 }),
        Object.freeze({ value: 41, cost: 380 }),
        Object.freeze({ value: 42, cost: 404 }),
        Object.freeze({ value: 43, cost: 428 }),
        Object.freeze({ value: 44, cost: 452 }),
        Object.freeze({ value: 45, cost: 476 }),
      ]),
      lab: Object.freeze({ growth: 1, max: 20 }),
      formatValue: seconds,
    }),
    Cooldown: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 300, cost: 0 }),
        Object.freeze({ value: 290, cost: 10 }),
        Object.freeze({ value: 280, cost: 28 }),
        Object.freeze({ value: 270, cost: 46 }),
        Object.freeze({ value: 260, cost: 64 }),
        Object.freeze({ value: 250, cost: 82 }),
        Object.freeze({ value: 240, cost: 100 }),
        Object.freeze({ value: 230, cost: 118 }),
        Object.freeze({ value: 220, cost: 136 }),
        Object.freeze({ value: 210, cost: 154 }),
        Object.freeze({ value: 200, cost: 172 }),
        Object.freeze({ value: 190, cost: 190 }),
        Object.freeze({ value: 180, cost: 208 }),
        Object.freeze({ value: 170, cost: 226 }),
        Object.freeze({ value: 160, cost: 244 }),
        Object.freeze({ value: 150, cost: 262 }),
        Object.freeze({ value: 140, cost: 300 }),
        Object.freeze({ value: 130, cost: 368 }),
        Object.freeze({ value: 120, cost: 476 }),
        Object.freeze({ value: 110, cost: 644 }),
        Object.freeze({ value: 100, cost: 872 }),
      ]),
      formatValue: seconds,
    }),
  }),
});

const SMART_MISSILES: UltimateWeapon = Object.freeze({
  upgrades: Object.freeze({
    Damage: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 14, cost: 0 }),
        Object.freeze({ value: 16, cost: 5 }),
        Object.freeze({ value: 19, cost: 11 }),
        Object.freeze({ value: 23, cost: 17 }),
        Object.freeze({ value: 27, cost: 23 }),
        Object.freeze({ value: 32, cost: 29 }),
        Object.freeze({ value: 39, cost: 35 }),
        Object.freeze({ value: 48, cost: 41 }),
        Object.freeze({ value: 59, cost: 47 }),
        Object.freeze({ value: 72, cost: 53 }),
        Object.freeze({ value: 88, cost: 61 }),
        Object.freeze({ value: 107, cost: 71 }),
        Object.freeze({ value: 129, cost: 84 }),
        Object.freeze({ value: 155, cost: 100 }),
        Object.freeze({ value: 185, cost: 120 }),
        Object.freeze({ value: 219, cost: 144 }),
        Object.freeze({ value: 257, cost: 174 }),
        Object.freeze({ value: 300, cost: 210 }),
        Object.freeze({ value: 349, cost: 252 }),
        Object.freeze({ value: 403, cost: 302 }),
        Object.freeze({ value: 462, cost: 362 }),
        Object.freeze({ value: 527, cost: 432 }),
        Object.freeze({ value: 599, cost: 528 }),
        Object.freeze({ value: 678, cost: 654 }),
        Object.freeze({ value: 763, cost: 810 }),
        Object.freeze({ value: 855, cost: 996 }),
        Object.freeze({ value: 955, cost: 1222 }),
        Object.freeze({ value: 1063, cost: 1488 }),
        Object.freeze({ value: 1179, cost: 1804 }),
        Object.freeze({ value: 1301, cost: 2180 }),
        Object.freeze({ value: 1436, cost: 2636 }),
      ]),
      formatValue: damageTimes,
    }),
    Quantity: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 5, cost: 0 }),
        Object.freeze({ value: 6, cost: 4 }),
        Object.freeze({ value: 7, cost: 12 }),
        Object.freeze({ value: 8, cost: 35 }),
        Object.freeze({ value: 9, cost: 70 }),
        Object.freeze({ value: 10, cost: 120 }),
        Object.freeze({ value: 11, cost: 180 }),
        Object.freeze({ value: 12, cost: 275 }),
        Object.freeze({ value: 13, cost: 350 }),
        Object.freeze({ value: 14, cost: 420 }),
        Object.freeze({ value: 15, cost: 500 }),
        Object.freeze({ value: 16, cost: 600 }),
        Object.freeze({ value: 17, cost: 750 }),
      ]),
      perk: (value: number) => value + 4,
      formatValue: quantity,
    }),
    Cooldown: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 180, cost: 0 }),
        Object.freeze({ value: 170, cost: 8 }),
        Object.freeze({ value: 160, cost: 24 }),
        Object.freeze({ value: 150, cost: 40 }),
        Object.freeze({ value: 140, cost: 56 }),
        Object.freeze({ value: 130, cost: 72 }),
        Object.freeze({ value: 120, cost: 88 }),
        Object.freeze({ value: 110, cost: 104 }),
        Object.freeze({ value: 100, cost: 120 }),
        Object.freeze({ value: 90, cost: 136 }),
        Object.freeze({ value: 80, cost: 152 }),
        Object.freeze({ value: 70, cost: 168 }),
        Object.freeze({ value: 60, cost: 184 }),
        Object.freeze({ value: 50, cost: 200 }),
        Object.freeze({ value: 40, cost: 216 }),
        Object.freeze({ value: 30, cost: 232 }),
      ]),
      formatValue: seconds,
    }),
  }),
});

const CHRONO_FIELD: UltimateWeapon = Object.freeze({
  upgrades: Object.freeze({
    Duration: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 5, cost: 0 }),
        Object.freeze({ value: 6, cost: 5 }),
        Object.freeze({ value: 7, cost: 14 }),
        Object.freeze({ value: 8, cost: 23 }),
        Object.freeze({ value: 9, cost: 32 }),
        Object.freeze({ value: 10, cost: 41 }),
        Object.freeze({ value: 11, cost: 50 }),
        Object.freeze({ value: 12, cost: 59 }),
        Object.freeze({ value: 13, cost: 68 }),
        Object.freeze({ value: 14, cost: 77 }),
        Object.freeze({ value: 15, cost: 86 }),
        Object.freeze({ value: 16, cost: 95 }),
        Object.freeze({ value: 17, cost: 104 }),
        Object.freeze({ value: 18, cost: 113 }),
        Object.freeze({ value: 19, cost: 122 }),
        Object.freeze({ value: 20, cost: 131 }),
        Object.freeze({ value: 21, cost: 140 }),
        Object.freeze({ value: 22, cost: 149 }),
        Object.freeze({ value: 23, cost: 158 }),
        Object.freeze({ value: 24, cost: 167 }),
        Object.freeze({ value: 25, cost: 176 }),
        Object.freeze({ value: 26, cost: 185 }),
        Object.freeze({ value: 27, cost: 194 }),
        Object.freeze({ value: 28, cost: 203 }),
        Object.freeze({ value: 29, cost: 212 }),
        Object.freeze({ value: 30, cost: 221 }),
        Object.freeze({ value: 31, cost: 230 }),
        Object.freeze({ value: 32, cost: 239 }),
        Object.freeze({ value: 33, cost: 248 }),
        Object.freeze({ value: 34, cost: 257 }),
        Object.freeze({ value: 35, cost: 266 }),
        Object.freeze({ value: 36, cost: 275 }),
        Object.freeze({ value: 37, cost: 284 }),
        Object.freeze({ value: 38, cost: 293 }),
        Object.freeze({ value: 39, cost: 302 }),
        Object.freeze({ value: 40, cost: 311 }),
      ]),
      lab: Object.freeze({ growth: 1, max: 30 }),
      formatValue: seconds,
    }),
    'Slow %': Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 20, cost: 0 }),
        Object.freeze({ value: 25, cost: 15 }),
        Object.freeze({ value: 30, cost: 25 }),
        Object.freeze({ value: 35, cost: 40 }),
        Object.freeze({ value: 40, cost: 60 }),
        Object.freeze({ value: 45, cost: 120 }),
        Object.freeze({ value: 50, cost: 150 }),
        Object.freeze({ value: 55, cost: 200 }),
        Object.freeze({ value: 60, cost: 300 }),
      ]),
      formatValue: slow,
    }),
    Cooldown: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 180, cost: 0 }),
        Object.freeze({ value: 170, cost: 10 }),
        Object.freeze({ value: 160, cost: 31 }),
        Object.freeze({ value: 150, cost: 52 }),
        Object.freeze({ value: 140, cost: 73 }),
        Object.freeze({ value: 130, cost: 94 }),
        Object.freeze({ value: 120, cost: 115 }),
        Object.freeze({ value: 110, cost: 136 }),
        Object.freeze({ value: 100, cost: 157 }),
        Object.freeze({ value: 90, cost: 178 }),
        Object.freeze({ value: 80, cost: 199 }),
        Object.freeze({ value: 70, cost: 220 }),
        Object.freeze({ value: 60, cost: 241 }),
      ]),
      formatValue: seconds,
    }),
  }),
});

const POISON_SWAMP: UltimateWeapon = Object.freeze({
  upgrades: Object.freeze({
    'Damage %': Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 150, cost: 0 }),
        Object.freeze({ value: 202, cost: 5 }),
        Object.freeze({ value: 257, cost: 11 }),
        Object.freeze({ value: 316, cost: 17 }),
        Object.freeze({ value: 378, cost: 23 }),
        Object.freeze({ value: 443, cost: 29 }),
        Object.freeze({ value: 510, cost: 35 }),
        Object.freeze({ value: 581, cost: 41 }),
        Object.freeze({ value: 654, cost: 47 }),
        Object.freeze({ value: 730, cost: 53 }),
        Object.freeze({ value: 809, cost: 61 }),
        Object.freeze({ value: 890, cost: 71 }),
        Object.freeze({ value: 975, cost: 84 }),
        Object.freeze({ value: 1062, cost: 100 }),
        Object.freeze({ value: 1151, cost: 120 }),
        Object.freeze({ value: 1243, cost: 144 }),
        Object.freeze({ value: 1338, cost: 174 }),
        Object.freeze({ value: 1435, cost: 210 }),
        Object.freeze({ value: 1535, cost: 252 }),
        Object.freeze({ value: 1638, cost: 302 }),
        Object.freeze({ value: 1743, cost: 362 }),
        Object.freeze({ value: 1850, cost: 434 }),
        Object.freeze({ value: 1961, cost: 525 }),
        Object.freeze({ value: 2073, cost: 636 }),
        Object.freeze({ value: 2188, cost: 772 }),
        Object.freeze({ value: 2306, cost: 938 }),
        Object.freeze({ value: 2426, cost: 1134 }),
        Object.freeze({ value: 2549, cost: 1360 }),
        Object.freeze({ value: 2674, cost: 1616 }),
        Object.freeze({ value: 2801, cost: 1902 }),
        Object.freeze({ value: 2931, cost: 2228 }),
      ]),
      formatValue: damage,
    }),
    Duration: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 2, cost: 0 }),
        Object.freeze({ value: 3, cost: 10 }),
        Object.freeze({ value: 4, cost: 20 }),
        Object.freeze({ value: 5, cost: 35 }),
        Object.freeze({ value: 6, cost: 55 }),
        Object.freeze({ value: 7, cost: 100 }),
        Object.freeze({ value: 8, cost: 120 }),
        Object.freeze({ value: 9, cost: 150 }),
        Object.freeze({ value: 10, cost: 200 }),
      ]),
      formatValue: seconds,
    }),
    'Chance %': Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 10, cost: 0 }),
        Object.freeze({ value: 13, cost: 8 }),
        Object.freeze({ value: 16, cost: 26 }),
        Object.freeze({ value: 19, cost: 44 }),
        Object.freeze({ value: 22, cost: 62 }),
        Object.freeze({ value: 25, cost: 80 }),
        Object.freeze({ value: 28, cost: 98 }),
        Object.freeze({ value: 31, cost: 116 }),
        Object.freeze({ value: 34, cost: 134 }),
        Object.freeze({ value: 37, cost: 152 }),
        Object.freeze({ value: 40, cost: 170 }),
        Object.freeze({ value: 43, cost: 188 }),
        Object.freeze({ value: 46, cost: 206 }),
        Object.freeze({ value: 49, cost: 224 }),
        Object.freeze({ value: 52, cost: 242 }),
        Object.freeze({ value: 55, cost: 260 }),
      ]),
      formatValue: chance,
    }),
  }),
});

const INNER_LAND_MINES: UltimateWeapon = Object.freeze({
  upgrades: Object.freeze({
    'Damage %': Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 2000, cost: 0 }),
        Object.freeze({ value: 2302, cost: 5 }),
        Object.freeze({ value: 2608, cost: 11 }),
        Object.freeze({ value: 2919, cost: 17 }),
        Object.freeze({ value: 3235, cost: 23 }),
        Object.freeze({ value: 3555, cost: 29 }),
        Object.freeze({ value: 3880, cost: 35 }),
        Object.freeze({ value: 4210, cost: 41 }),
        Object.freeze({ value: 4545, cost: 47 }),
        Object.freeze({ value: 4885, cost: 53 }),
        Object.freeze({ value: 5230, cost: 61 }),
        Object.freeze({ value: 5579, cost: 71 }),
        Object.freeze({ value: 5934, cost: 84 }),
        Object.freeze({ value: 6294, cost: 100 }),
        Object.freeze({ value: 6659, cost: 120 }),
        Object.freeze({ value: 7029, cost: 144 }),
        Object.freeze({ value: 7405, cost: 174 }),
        Object.freeze({ value: 7785, cost: 210 }),
        Object.freeze({ value: 8171, cost: 254 }),
        Object.freeze({ value: 8562, cost: 308 }),
        Object.freeze({ value: 8958, cost: 374 }),
        Object.freeze({ value: 9359, cost: 454 }),
        Object.freeze({ value: 9765, cost: 540 }),
        Object.freeze({ value: 10177, cost: 632 }),
        Object.freeze({ value: 10594, cost: 730 }),
        Object.freeze({ value: 11016, cost: 834 }),
        Object.freeze({ value: 11444, cost: 944 }),
        Object.freeze({ value: 11877, cost: 1060 }),
        Object.freeze({ value: 12315, cost: 1182 }),
        Object.freeze({ value: 12759, cost: 1312 }),
        Object.freeze({ value: 13207, cost: 1448 }),
      ]),
      formatValue: damage,
    }),
    Quantity: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 3, cost: 0 }),
        Object.freeze({ value: 4, cost: 50 }),
        Object.freeze({ value: 5, cost: 125 }),
        Object.freeze({ value: 6, cost: 250 }),
      ]),
      perk: (value: number) => value + 6,
      formatValue: quantity,
    }),
    Cooldown: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 200, cost: 0 }),
        Object.freeze({ value: 190, cost: 8 }),
        Object.freeze({ value: 180, cost: 24 }),
        Object.freeze({ value: 170, cost: 40 }),
        Object.freeze({ value: 160, cost: 56 }),
        Object.freeze({ value: 150, cost: 72 }),
        Object.freeze({ value: 140, cost: 88 }),
        Object.freeze({ value: 130, cost: 104 }),
        Object.freeze({ value: 120, cost: 120 }),
        Object.freeze({ value: 110, cost: 136 }),
        Object.freeze({ value: 100, cost: 152 }),
        Object.freeze({ value: 90, cost: 168 }),
        Object.freeze({ value: 80, cost: 184 }),
        Object.freeze({ value: 70, cost: 200 }),
        Object.freeze({ value: 60, cost: 216 }),
        Object.freeze({ value: 50, cost: 232 }),
      ]),
      formatValue: seconds,
    }),
  }),
});

const CHAIN_LIGHTNING: UltimateWeapon = Object.freeze({
  upgrades: Object.freeze({
    'Damage %': Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 110, cost: 0 }),
        Object.freeze({ value: 142, cost: 5 }),
        Object.freeze({ value: 180, cost: 11 }),
        Object.freeze({ value: 225, cost: 17 }),
        Object.freeze({ value: 279, cost: 23 }),
        Object.freeze({ value: 341, cost: 29 }),
        Object.freeze({ value: 413, cost: 35 }),
        Object.freeze({ value: 496, cost: 41 }),
        Object.freeze({ value: 589, cost: 47 }),
        Object.freeze({ value: 693, cost: 53 }),
        Object.freeze({ value: 809, cost: 61 }),
        Object.freeze({ value: 937, cost: 71 }),
        Object.freeze({ value: 1077, cost: 84 }),
        Object.freeze({ value: 1230, cost: 100 }),
        Object.freeze({ value: 1395, cost: 120 }),
        Object.freeze({ value: 1574, cost: 144 }),
        Object.freeze({ value: 1766, cost: 174 }),
        Object.freeze({ value: 1972, cost: 210 }),
        Object.freeze({ value: 2192, cost: 252 }),
        Object.freeze({ value: 2426, cost: 302 }),
        Object.freeze({ value: 2675, cost: 362 }),
        Object.freeze({ value: 2939, cost: 434 }),
        Object.freeze({ value: 3217, cost: 525 }),
        Object.freeze({ value: 3510, cost: 636 }),
        Object.freeze({ value: 3819, cost: 767 }),
        Object.freeze({ value: 4143, cost: 923 }),
        Object.freeze({ value: 4483, cost: 1109 }),
        Object.freeze({ value: 4839, cost: 1295 }),
        Object.freeze({ value: 5211, cost: 1521 }),
        Object.freeze({ value: 5599, cost: 1787 }),
        Object.freeze({ value: 6004, cost: 2103 }),
      ]),
      perk: (value: number) => value * 2,
      formatValue: damage,
    }),
    Bolts: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 1, cost: 0 }),
        Object.freeze({ value: 2, cost: 30 }),
        Object.freeze({ value: 3, cost: 75 }),
        Object.freeze({ value: 4, cost: 150 }),
        Object.freeze({ value: 5, cost: 400 }),
      ]),
      formatValue: quantity,
    }),
    'Chance %': Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 5.0, cost: 0 }),
        Object.freeze({ value: 6.5, cost: 8 }),
        Object.freeze({ value: 8.0, cost: 26 }),
        Object.freeze({ value: 9.5, cost: 44 }),
        Object.freeze({ value: 11.0, cost: 62 }),
        Object.freeze({ value: 12.5, cost: 80 }),
        Object.freeze({ value: 14.0, cost: 98 }),
        Object.freeze({ value: 15.5, cost: 116 }),
        Object.freeze({ value: 17.0, cost: 134 }),
        Object.freeze({ value: 18.5, cost: 152 }),
        Object.freeze({ value: 20.0, cost: 170 }),
        Object.freeze({ value: 21.5, cost: 188 }),
        Object.freeze({ value: 23.0, cost: 206 }),
        Object.freeze({ value: 24.5, cost: 224 }),
        Object.freeze({ value: 26.0, cost: 242 }),
        Object.freeze({ value: 27.5, cost: 260 }),
      ]),
      formatValue: chance,
    }),
  }),
});

const SPOTLIGHT: UltimateWeapon = Object.freeze({
  upgrades: Object.freeze({
    Bonus: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 8, cost: 0 }),
        Object.freeze({ value: 9.4, cost: 5 }),
        Object.freeze({ value: 10.8, cost: 13 }),
        Object.freeze({ value: 12.2, cost: 21 }),
        Object.freeze({ value: 13.6, cost: 30 }),
        Object.freeze({ value: 15, cost: 40 }),
        Object.freeze({ value: 16.4, cost: 52 }),
        Object.freeze({ value: 17.8, cost: 65 }),
        Object.freeze({ value: 19.2, cost: 80 }),
        Object.freeze({ value: 20.6, cost: 95 }),
        Object.freeze({ value: 22, cost: 112 }),
        Object.freeze({ value: 23.4, cost: 133 }),
        Object.freeze({ value: 24.8, cost: 150 }),
        Object.freeze({ value: 26.2, cost: 180 }),
        Object.freeze({ value: 27.6, cost: 220 }),
        Object.freeze({ value: 29, cost: 280 }),
        Object.freeze({ value: 30.4, cost: 320 }),
        Object.freeze({ value: 31.8, cost: 360 }),
        Object.freeze({ value: 33.2, cost: 420 }),
        Object.freeze({ value: 34.6, cost: 500 }),
        Object.freeze({ value: 36, cost: 600 }),
        Object.freeze({ value: 37.4, cost: 720 }),
        Object.freeze({ value: 38.8, cost: 850 }),
        Object.freeze({ value: 40.2, cost: 1000 }),
        Object.freeze({ value: 41.6, cost: 1175 }),
        Object.freeze({ value: 43, cost: 1400 }),
      ]),
      perk: (value: number) => value * 1.5,
      formatValue: bonus,
    }),
    Angle: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 30, cost: 0 }),
        Object.freeze({ value: 31, cost: 5 }),
        Object.freeze({ value: 32, cost: 16 }),
        Object.freeze({ value: 33, cost: 27 }),
        Object.freeze({ value: 34, cost: 38 }),
        Object.freeze({ value: 35, cost: 49 }),
        Object.freeze({ value: 36, cost: 60 }),
        Object.freeze({ value: 37, cost: 71 }),
        Object.freeze({ value: 38, cost: 82 }),
        Object.freeze({ value: 39, cost: 93 }),
        Object.freeze({ value: 40, cost: 104 }),
        Object.freeze({ value: 41, cost: 115 }),
        Object.freeze({ value: 42, cost: 126 }),
        Object.freeze({ value: 43, cost: 137 }),
        Object.freeze({ value: 44, cost: 148 }),
        Object.freeze({ value: 45, cost: 159 }),
        Object.freeze({ value: 46, cost: 170 }),
        Object.freeze({ value: 47, cost: 181 }),
        Object.freeze({ value: 48, cost: 192 }),
        Object.freeze({ value: 49, cost: 203 }),
        Object.freeze({ value: 50, cost: 214 }),
        Object.freeze({ value: 51, cost: 225 }),
        Object.freeze({ value: 52, cost: 236 }),
        Object.freeze({ value: 53, cost: 247 }),
        Object.freeze({ value: 54, cost: 258 }),
        Object.freeze({ value: 55, cost: 269 }),
        Object.freeze({ value: 56, cost: 280 }),
        Object.freeze({ value: 57, cost: 291 }),
        Object.freeze({ value: 58, cost: 302 }),
        Object.freeze({ value: 59, cost: 313 }),
        Object.freeze({ value: 60, cost: 324 }),
      ]),
      formatValue: quantity,
    }),
    Quantity: Object.freeze({
      values: Object.freeze([
        Object.freeze({ value: 1, cost: 0 }),
        Object.freeze({ value: 2, cost: 375 }),
        Object.freeze({ value: 3, cost: 850 }),
      ]),
      formatValue: quantity,
    }),
  }),
});

export const ULTIMATE_WEAPONS: UltimateWeapons = Object.freeze({
  'Death Wave': DEATH_WAVE,
  'Black Hole': BLACK_HOLE,
  'Golden Tower': GOLDEN_TOWER,
  'Smart Missiles': SMART_MISSILES,
  'Chrono Field': CHRONO_FIELD,
  'Poison Swamp': POISON_SWAMP,
  'Inner Land Mines': INNER_LAND_MINES,
  'Chain Lightning': CHAIN_LIGHTNING,
  Spotlight: SPOTLIGHT,
});

export const UNLOCK_COSTS = [5, 50, 150, 300, 800, 1250, 1750, 2400, 3000];
