const COIN = 1;
const K = 1000 * COIN;
const M = 1000 * K;
const B = 1000 * M;
const T = 1000 * B;
const QUAD = 1000 * T;
const QUINT = 1000 * QUAD;

const upgrade = (
  name: string,
  min: number,
  max: number,
  quantity: number,
  cost: number,
) =>
  Object.freeze({
    name,
    min,
    max,
    quantity,
    cost,
  });

// Attack Tab

export const BASE_DAMAGE_MIN = 3;
export const BASE_DAMAGE_MAX = 71114385.08;
export const BASE_DAMAGE_QUANTITY = 6000;
export const BASE_DAMAGE_COST = 816.09 * T;
export const DAMAGE = upgrade(
  'Damage',
  BASE_DAMAGE_MIN,
  BASE_DAMAGE_MAX,
  BASE_DAMAGE_QUANTITY,
  BASE_DAMAGE_COST,
);

export const BASE_ASPD_MIN = 1.0;
export const BASE_ASPD_MAX = 5.95;
export const BASE_ASPD_QUANTITY = 99;
export const BASE_ASPD_COST = 3.6 * M;
export const ASPD = upgrade(
  'Attack Speed',
  BASE_ASPD_MIN,
  BASE_ASPD_MAX,
  BASE_ASPD_QUANTITY,
  BASE_ASPD_COST,
);

export const BASE_CRIT_CHANCE_MIN = 1;
export const BASE_CRIT_CHANCE_MAX = 80;
export const BASE_CRIT_CHANCE_QUANTITY = 79;
export const BASE_CRIT_CHANCE_COST = 1.41 * M;
export const CRIT_CHANCE = upgrade(
  'Critical Chance',
  BASE_CRIT_CHANCE_MIN,
  BASE_CRIT_CHANCE_MAX,
  BASE_CRIT_CHANCE_QUANTITY,
  BASE_CRIT_CHANCE_COST,
);

export const BASE_CRIT_FACTOR_MIN = 1.2;
export const BASE_CRIT_FACTOR_MAX = 16.2;
export const BASE_CRIT_FACTOR_QUANTITY = 150;
export const BASE_CRIT_FACTOR_COST = 259.2 * B;
export const CRIT_FACTOR = upgrade(
  'Critical Factor',
  BASE_CRIT_FACTOR_MIN,
  BASE_CRIT_FACTOR_MAX,
  BASE_CRIT_FACTOR_QUANTITY,
  BASE_CRIT_FACTOR_COST,
);

export const BASE_RANGE_MIN = 30;
export const BASE_RANGE_MAX = 69.5;
export const BASE_RANGE_QUANTITY = 79;
export const BASE_RANGE_COST = 1.46 * M;
export const RANGE = upgrade(
  'Attack Range',
  BASE_RANGE_MIN,
  BASE_RANGE_MAX,
  BASE_RANGE_QUANTITY,
  BASE_RANGE_COST,
);

export const BASE_DPM_MIN = 0;
export const BASE_DPM_MAX = 59;
export const BASE_DPM_QUANTITY = 200;
export const BASE_DPM_COST = 316.5 * T;
export const DPM = upgrade(
  'Damage / Meter',
  BASE_DPM_MIN,
  BASE_DPM_MAX,
  BASE_DPM_QUANTITY,
  BASE_DPM_COST,
);

export const BASE_MULTISHOT_CHANCE_MIN = 0;
export const BASE_MULTISHOT_CHANCE_MAX = 49.5;
export const BASE_MULTISHOT_CHANCE_QUANTITY = 99;
export const BASE_MULTISHOT_CHANCE_COST = 4.26 * M;
export const MULTISHOT_CHANCE = upgrade(
  'Multishot Chance',
  BASE_MULTISHOT_CHANCE_MIN,
  BASE_MULTISHOT_CHANCE_MAX,
  BASE_MULTISHOT_CHANCE_QUANTITY,
  BASE_MULTISHOT_CHANCE_COST,
);

export const BASE_MULTISHOT_TARGETS_MIN = 2;
export const BASE_MULTISHOT_TARGETS_MAX = 9;
export const BASE_MULTISHOT_TARGETS_QUANTITY = 7;
export const BASE_MULTISHOT_TARGETS_COST = 529.95 * K;
export const MULTISHOT_TARGETS = upgrade(
  'Multishot Targets',
  BASE_MULTISHOT_TARGETS_MIN,
  BASE_MULTISHOT_TARGETS_MAX,
  BASE_MULTISHOT_TARGETS_QUANTITY,
  BASE_MULTISHOT_TARGETS_COST,
);

export const BASE_RAPIDFIRE_CHANCE_MIN = 0;
export const BASE_RAPIDFIRE_CHANCE_MAX = 34;
export const BASE_RAPIDFIRE_CHANCE_QUANTITY = 85;
export const BASE_RAPIDFIRE_CHANCE_COST = 3.23 * M;
export const RAPIDFIRE_CHANCE = upgrade(
  'Rapid Fire Chance',
  BASE_RAPIDFIRE_CHANCE_MIN,
  BASE_RAPIDFIRE_CHANCE_MAX,
  BASE_RAPIDFIRE_CHANCE_QUANTITY,
  BASE_RAPIDFIRE_CHANCE_COST,
);

export const BASE_RAPIDFIRE_DURATION_MIN = 0.6;
export const BASE_RAPIDFIRE_DURATION_MAX = 5.55;
export const BASE_RAPIDFIRE_DURATION_QUANTITY = 99;
export const BASE_RAPIDFIRE_DURATION_COST = 4.63 * M;
export const RAPIDFIRE_DURATION = upgrade(
  'Rapid Fire Duration',
  BASE_RAPIDFIRE_DURATION_MIN,
  BASE_RAPIDFIRE_DURATION_MAX,
  BASE_RAPIDFIRE_DURATION_QUANTITY,
  BASE_RAPIDFIRE_DURATION_COST,
);

export const BASE_BOUNCE_SHOT_CHANCE_MIN = 0;
export const BASE_BOUNCE_SHOT_CHANCE_MAX = 68;
export const BASE_BOUNCE_SHOT_CHANCE_QUANTITY = 85;
export const BASE_BOUNCE_SHOT_CHANCE_COST = 3.23 * M;
export const BOUNCE_SHOT_CHANCE = upgrade(
  'Bounce Shot Chance',
  BASE_BOUNCE_SHOT_CHANCE_MIN,
  BASE_BOUNCE_SHOT_CHANCE_MAX,
  BASE_BOUNCE_SHOT_CHANCE_QUANTITY,
  BASE_BOUNCE_SHOT_CHANCE_COST,
);

export const BASE_BOUNCE_SHOT_TARGETS_MIN = 1;
export const BASE_BOUNCE_SHOT_TARGETS_MAX = 8;
export const BASE_BOUNCE_SHOT_TARGETS_QUANTITY = 7;
export const BASE_BOUNCE_SHOT_TARGETS_COST = 970.7 * K;
export const BOUNCE_SHOT_TARGETS = upgrade(
  'Bounce Shot Targets',
  BASE_BOUNCE_SHOT_TARGETS_MIN,
  BASE_BOUNCE_SHOT_TARGETS_MAX,
  BASE_BOUNCE_SHOT_TARGETS_QUANTITY,
  BASE_BOUNCE_SHOT_TARGETS_COST,
);

export const BASE_BOUNCE_SHOT_RANGE_MIN = 0;
export const BASE_BOUNCE_SHOT_RANGE_MAX = 8;
export const BASE_BOUNCE_SHOT_RANGE_QUANTITY = 60;
export const BASE_BOUNCE_SHOT_RANGE_COST = 3.81 * T;
export const BOUNCE_SHOT_RANGE = upgrade(
  'Bounce Shot Range',
  BASE_BOUNCE_SHOT_RANGE_MIN,
  BASE_BOUNCE_SHOT_RANGE_MAX,
  BASE_BOUNCE_SHOT_RANGE_QUANTITY,
  BASE_BOUNCE_SHOT_RANGE_COST,
);

export const BASE_SCC_MIN = 0;
export const BASE_SCC_MAX = 20;
export const BASE_SCC_QUANTITY = 100;
export const BASE_SCC_COST = 5.63 * T;
export const SCC = upgrade(
  'Super Crit Chance',
  BASE_SCC_MIN,
  BASE_SCC_MAX,
  BASE_SCC_QUANTITY,
  BASE_SCC_COST,
);

export const BASE_SCM_MIN = 1.2;
export const BASE_SCM_MAX = 13.2;
export const BASE_SCM_QUANTITY = 120;
export const BASE_SCM_COST = 214.5 * T;
export const SCM = upgrade(
  'Super Crit Mult',
  BASE_SCM_MIN,
  BASE_SCM_MAX,
  BASE_SCM_QUANTITY,
  BASE_SCM_COST,
);

export const BASE_REND_CHANCE_MIN = 0.1;
export const BASE_REND_CHANCE_MAX = 30;
export const BASE_REND_CHANCE_QUANTITY = 200;
export const BASE_REND_CHANCE_COST = 418.97 * QUAD;
export const REND_CHANCE = upgrade(
  'Rend Armor Chance',
  BASE_REND_CHANCE_MIN,
  BASE_REND_CHANCE_MAX,
  BASE_REND_CHANCE_QUANTITY,
  BASE_REND_CHANCE_COST,
);

export const BASE_REND_MULT_MIN = 0.1;
export const BASE_REND_MULT_MAX = 30;
export const BASE_REND_MULT_QUANTITY = 299;
export const BASE_REND_MULT_COST = 15.34 * QUINT;
export const REND_MULT = upgrade(
  'Rend Armor Mult',
  BASE_REND_MULT_MIN,
  BASE_REND_MULT_MAX,
  BASE_REND_MULT_QUANTITY,
  BASE_REND_MULT_COST,
);

export const BASE_REND_CAP_MAX = 800;

export const ATTACK_UPGRADES = Object.freeze({
  [DAMAGE.name]: DAMAGE,
  [ASPD.name]: ASPD,
  [CRIT_CHANCE.name]: CRIT_CHANCE,
  [CRIT_FACTOR.name]: CRIT_FACTOR,
  [RANGE.name]: RANGE,
  [DPM.name]: DPM,
  [MULTISHOT_CHANCE.name]: MULTISHOT_CHANCE,
  [MULTISHOT_TARGETS.name]: MULTISHOT_TARGETS,
  [RAPIDFIRE_CHANCE.name]: RAPIDFIRE_CHANCE,
  [RAPIDFIRE_DURATION.name]: RAPIDFIRE_DURATION,
  [BOUNCE_SHOT_CHANCE.name]: BOUNCE_SHOT_CHANCE,
  [BOUNCE_SHOT_TARGETS.name]: BOUNCE_SHOT_TARGETS,
  [BOUNCE_SHOT_RANGE.name]: BOUNCE_SHOT_RANGE,
  [SCC.name]: SCC,
  [SCM.name]: SCM,
  [REND_CHANCE.name]: REND_CHANCE,
  [REND_MULT.name]: REND_MULT,
});

// Defense Tab

export const BASE_HP_MIN = 1;
export const BASE_HP_MAX = 912646158.329498;
export const BASE_HP_QUANTITY = 5000;
export const BASE_HP_COST = 1.23 * T;
export const HP = upgrade(
  'Health',
  BASE_HP_MIN,
  BASE_HP_MAX,
  BASE_HP_QUANTITY,
  BASE_HP_COST,
);

export const BASE_REGEN_MIN = 1;
export const BASE_REGEN_MAX = 523233008.7;
export const BASE_REGEN_QUANTITY = 5000;
export const BASE_REGEN_COST = 1.23 * T;
export const REGEN = upgrade(
  'Health Regen',
  BASE_REGEN_MIN,
  BASE_REGEN_MAX,
  BASE_REGEN_QUANTITY,
  BASE_REGEN_COST,
);

export const BASE_DEF_PERCENT_MIN = 0;
export const BASE_DEF_PERCENT_MAX = 49.5;
export const BASE_DEF_PERCENT_QUANTITY = 99;
export const BASE_DEF_PERCENT_COST = 2.77 * M;
export const DEF_PERCENT = upgrade(
  'Defense %',
  BASE_DEF_PERCENT_MIN,
  BASE_DEF_PERCENT_MAX,
  BASE_DEF_PERCENT_QUANTITY,
  BASE_DEF_PERCENT_COST,
);

export const BASE_DEF_ABSOLUTE_MIN = 0;
export const BASE_DEF_ABSOLUTE_MAX = 80214388.0521576;
export const BASE_DEF_ABSOLUTE_QUANTITY = 5000;
export const BASE_DEF_ABSOLUTE_COST = 1.23 * T;
export const DEF_ABSOLUTE = upgrade(
  'Defense Absolute',
  BASE_DEF_ABSOLUTE_MIN,
  BASE_DEF_ABSOLUTE_MAX,
  BASE_DEF_ABSOLUTE_QUANTITY,
  BASE_DEF_ABSOLUTE_COST,
);

export const BASE_THORN_MIN = 0;
export const BASE_THORN_MAX = 99;
export const BASE_THORN_QUANTITY = 99;
export const BASE_THORN_COST = 2.33 * M;
export const THORN = upgrade(
  'Thorn Damage',
  BASE_THORN_MIN,
  BASE_THORN_MAX,
  BASE_THORN_QUANTITY,
  BASE_THORN_COST,
);

export const BASE_LIFESTEAL_MIN = 0;
export const BASE_LIFESTEAL_MAX = 4.46;
export const BASE_LIFESTEAL_QUANTITY = 80;
export const BASE_LIFESTEAL_COST = 1.48 * M;
export const LIFESTEAL = upgrade(
  'Lifesteal',
  BASE_LIFESTEAL_MIN,
  BASE_LIFESTEAL_MAX,
  BASE_LIFESTEAL_QUANTITY,
  BASE_LIFESTEAL_COST,
);

export const BASE_KNOCKBACK_CHANCE_MIN = 0;
export const BASE_KNOCKBACK_CHANCE_MAX = 80;
export const BASE_KNOCKBACK_CHANCE_QUANTITY = 80;
export const BASE_KNOCKBACK_CHANCE_COST = 1.6 * M;
export const KNOCKBACK_CHANCE = upgrade(
  'Knockback Chance',
  BASE_KNOCKBACK_CHANCE_MIN,
  BASE_KNOCKBACK_CHANCE_MAX,
  BASE_KNOCKBACK_CHANCE_QUANTITY,
  BASE_KNOCKBACK_CHANCE_COST,
);

export const BASE_KNOCKBACK_FORCE_MIN = 0.4;
export const BASE_KNOCKBACK_FORCE_MAX = 6.08;
export const BASE_KNOCKBACK_FORCE_QUANTITY = 40;
export const BASE_KNOCKBACK_FORCE_COST = 184.33 * K;
export const KNOCKBACK_FORCE = upgrade(
  'Knockback Force',
  BASE_KNOCKBACK_FORCE_MIN,
  BASE_KNOCKBACK_FORCE_MAX,
  BASE_KNOCKBACK_FORCE_QUANTITY,
  BASE_KNOCKBACK_FORCE_COST,
);

export const BASE_ORB_SPEED_MIN = 0.4;
export const BASE_ORB_SPEED_MAX = 6.1;
export const BASE_ORB_SPEED_QUANTITY = 38;
export const BASE_ORB_SPEED_COST = 342.98 * K;
export const ORB_SPEED = upgrade(
  'Orb Speed',
  BASE_ORB_SPEED_MIN,
  BASE_ORB_SPEED_MAX,
  BASE_ORB_SPEED_QUANTITY,
  BASE_ORB_SPEED_COST,
);

export const BASE_ORB_QUANTITY_MIN = 0;
export const BASE_ORB_QUANTITY_MAX = 4;
export const BASE_ORB_QUANTITY_QUANTITY = 4;
export const BASE_ORB_QUANTITY_COST = 493.0 * K;
export const ORB_QUANTITY = upgrade(
  'Orbs',
  BASE_ORB_QUANTITY_MIN,
  BASE_ORB_QUANTITY_MAX,
  BASE_ORB_QUANTITY_QUANTITY,
  BASE_ORB_QUANTITY_COST,
);

export const WORKSHOP_ORB_DISTANCE = 75;

export const BASE_SHOCKWAVE_SIZE_MIN = 0.6;
export const BASE_SHOCKWAVE_SIZE_MAX = 2.35;
export const BASE_SHOCKWAVE_SIZE_QUANTITY = 35;
export const BASE_SHOCKWAVE_SIZE_COST = 600.13 * K;
export const SHOCKWAVE_SIZE = upgrade(
  'Shockwave Size',
  BASE_SHOCKWAVE_SIZE_MIN,
  BASE_SHOCKWAVE_SIZE_MAX,
  BASE_SHOCKWAVE_SIZE_QUANTITY,
  BASE_SHOCKWAVE_SIZE_COST,
);

export const BASE_SHOCKWAVE_FREQUENCY_MIN = 20;
export const BASE_SHOCKWAVE_FREQUENCY_MAX = 14;
export const BASE_SHOCKWAVE_FREQUENCY_QUANTITY = 40;
export const BASE_SHOCKWAVE_FREQUENCY_COST = 973.74 * K;
export const SHOCKWAVE_FREQUENCY = upgrade(
  'Shockwave Frequency',
  BASE_SHOCKWAVE_FREQUENCY_MIN,
  BASE_SHOCKWAVE_FREQUENCY_MAX,
  BASE_SHOCKWAVE_FREQUENCY_QUANTITY,
  BASE_SHOCKWAVE_FREQUENCY_COST,
);

export const BASE_LAND_MINE_CHANCE_MIN = 0;
export const BASE_LAND_MINE_CHANCE_MAX = 30;
export const BASE_LAND_MINE_CHANCE_QUANTITY = 50;
export const BASE_LAND_MINE_CHANCE_COST = 15.46 * M;
export const LAND_MINE_CHANCE = upgrade(
  'Land Mine Chance',
  BASE_LAND_MINE_CHANCE_MIN,
  BASE_LAND_MINE_CHANCE_MAX,
  BASE_LAND_MINE_CHANCE_QUANTITY,
  BASE_LAND_MINE_CHANCE_COST,
);

export const BASE_LAND_MINE_DAMAGE_MIN = 100;
export const BASE_LAND_MINE_DAMAGE_MAX = 2100;
export const BASE_LAND_MINE_DAMAGE_QUANTITY = 200;
export const BASE_LAND_MINE_DAMAGE_COST = 2.45 * QUAD;
export const LAND_MINE_DAMAGE = upgrade(
  'Land Mine Damage',
  BASE_LAND_MINE_DAMAGE_MIN,
  BASE_LAND_MINE_DAMAGE_MAX,
  BASE_LAND_MINE_DAMAGE_QUANTITY,
  BASE_LAND_MINE_DAMAGE_COST,
);

export const BASE_LAND_MINE_RADIUS_MIN = 0.5;
export const BASE_LAND_MINE_RADIUS_MAX = 1.5;
export const BASE_LAND_MINE_RADIUS_QUANTITY = 50;
export const BASE_LAND_MINE_RADIUS_COST = 77.52 * B;
export const LAND_MINE_RADIUS = upgrade(
  'Land Mine Radius',
  BASE_LAND_MINE_RADIUS_MIN,
  BASE_LAND_MINE_RADIUS_MAX,
  BASE_LAND_MINE_RADIUS_QUANTITY,
  BASE_LAND_MINE_RADIUS_COST,
);

export const BASE_DEATH_DEFY_MIN = 0;
export const BASE_DEATH_DEFY_MAX = 30;
export const BASE_DEATH_DEFY_QUANTITY = 75;
export const BASE_DEATH_DEFY_COST = 1.72 * B;
export const DEATH_DEFY = upgrade(
  'Death Defy',
  BASE_DEATH_DEFY_MIN,
  BASE_DEATH_DEFY_MAX,
  BASE_DEATH_DEFY_QUANTITY,
  BASE_DEATH_DEFY_COST,
);

export const BASE_WALL_HEALTH_MIN = 20;
export const BASE_WALL_HEALTH_MAX = 200;
export const BASE_WALL_HEALTH_QUANTITY = 1800;
export const BASE_WALL_HEALTH_COST = 14.59 * QUAD;
export const WALL_HEALTH = upgrade(
  'Wall Health',
  BASE_WALL_HEALTH_MIN,
  BASE_WALL_HEALTH_MAX,
  BASE_WALL_HEALTH_QUANTITY,
  BASE_WALL_HEALTH_COST,
);

export const BASE_WALL_REBUILD_MIN = 1200;
export const BASE_WALL_REBUILD_MAX = 600;
export const BASE_WALL_REBUILD_QUANTITY = 300;
export const BASE_WALL_REBUILD_COST = 40.37 * T;
export const WALL_REBUILD = upgrade(
  'Wall Rebuild',
  BASE_WALL_REBUILD_MIN,
  BASE_WALL_REBUILD_MAX,
  BASE_WALL_REBUILD_QUANTITY,
  BASE_WALL_REBUILD_COST,
);

export const DEFENSE_UPGRADES = Object.freeze({
  [HP.name]: HP,
  [REGEN.name]: REGEN,
  [DEF_PERCENT.name]: DEF_PERCENT,
  [DEF_ABSOLUTE.name]: DEF_ABSOLUTE,
  [THORN.name]: THORN,
  [LIFESTEAL.name]: LIFESTEAL,
  [KNOCKBACK_CHANCE.name]: KNOCKBACK_CHANCE,
  [KNOCKBACK_FORCE.name]: KNOCKBACK_FORCE,
  [ORB_SPEED.name]: ORB_SPEED,
  [ORB_QUANTITY.name]: ORB_QUANTITY,
  [SHOCKWAVE_SIZE.name]: SHOCKWAVE_SIZE,
  [SHOCKWAVE_FREQUENCY.name]: SHOCKWAVE_FREQUENCY,
  [LAND_MINE_CHANCE.name]: LAND_MINE_CHANCE,
  [LAND_MINE_DAMAGE.name]: LAND_MINE_DAMAGE,
  [LAND_MINE_RADIUS.name]: LAND_MINE_RADIUS,
  [DEATH_DEFY.name]: DEATH_DEFY,
  [WALL_HEALTH.name]: WALL_HEALTH,
  [WALL_REBUILD.name]: WALL_REBUILD,
});

// Utility Tab

export const BASE_CASH_BONUS_MIN = 1;
export const BASE_CASH_BONUS_MAX = 2.49;
export const BASE_CASH_BONUS_QUANTITY = 149;
export const BASE_CASH_BONUS_COST = 14.82 * M;
export const CASH_BONUS = upgrade(
  'Cash Bonus',
  BASE_CASH_BONUS_MIN,
  BASE_CASH_BONUS_MAX,
  BASE_CASH_BONUS_QUANTITY,
  BASE_CASH_BONUS_COST,
);

export const BASE_CASH_PER_WAVE_MIN = 0;
export const BASE_CASH_PER_WAVE_MAX = 596;
export const BASE_CASH_PER_WAVE_QUANTITY = 149;
export const BASE_CASH_PER_WAVE_COST = 14.82 * M;
export const CASH_PER_WAVE = upgrade(
  'Cash / Wave',
  BASE_CASH_PER_WAVE_MIN,
  BASE_CASH_PER_WAVE_MAX,
  BASE_CASH_PER_WAVE_QUANTITY,
  BASE_CASH_PER_WAVE_COST,
);

export const BASE_COINS_PER_KILL_MIN = 1;
export const BASE_COINS_PER_KILL_MAX = 2.49;
export const BASE_COINS_PER_KILL_QUANTITY = 149;
export const BASE_COINS_PER_KILL_COST = 19.47 * M;
export const COINS_PER_KILL = upgrade(
  'Coins / Kill Bonus',
  BASE_COINS_PER_KILL_MIN,
  BASE_COINS_PER_KILL_MAX,
  BASE_COINS_PER_KILL_QUANTITY,
  BASE_COINS_PER_KILL_COST,
);

export const BASE_COINS_PER_WAVE_MIN = 1;
export const BASE_COINS_PER_WAVE_MAX = 150;
export const BASE_COINS_PER_WAVE_QUANTITY = 149;
export const BASE_COINS_PER_WAVE_COST = 19.47 * M;
export const COINS_PER_WAVE = upgrade(
  'Coins / Wave',
  BASE_COINS_PER_WAVE_MIN,
  BASE_COINS_PER_WAVE_MAX,
  BASE_COINS_PER_WAVE_QUANTITY,
  BASE_COINS_PER_WAVE_COST,
);

export const BASE_FREE_ATTACK_UPGRADE_MIN = 0;
export const BASE_FREE_ATTACK_UPGRADE_MAX = 49.5;
export const BASE_FREE_ATTACK_UPGRADE_QUANTITY = 99;
export const BASE_FREE_ATTACK_UPGRADE_COST = 4.05 * M;
export const FREE_ATTACK_UPGRADE = upgrade(
  'Free Attack Upgrade',
  BASE_FREE_ATTACK_UPGRADE_MIN,
  BASE_FREE_ATTACK_UPGRADE_MAX,
  BASE_FREE_ATTACK_UPGRADE_QUANTITY,
  BASE_FREE_ATTACK_UPGRADE_COST,
);

export const BASE_FREE_DEFENSE_UPGRADE_MIN = 0;
export const BASE_FREE_DEFENSE_UPGRADE_MAX = 49.5;
export const BASE_FREE_DEFENSE_UPGRADE_QUANTITY = 99;
export const BASE_FREE_DEFENSE_UPGRADE_COST = 4.05 * M;
export const FREE_DEFENSE_UPGRADE = upgrade(
  'Free Defense Upgrade',
  BASE_FREE_DEFENSE_UPGRADE_MIN,
  BASE_FREE_DEFENSE_UPGRADE_MAX,
  BASE_FREE_DEFENSE_UPGRADE_QUANTITY,
  BASE_FREE_DEFENSE_UPGRADE_COST,
);

export const BASE_FREE_UTILITY_UPGRADE_MIN = 0;
export const BASE_FREE_UTILITY_UPGRADE_MAX = 49.5;
export const BASE_FREE_UTILITY_UPGRADE_QUANTITY = 99;
export const BASE_FREE_UTILITY_UPGRADE_COST = 4.05 * M;
export const FREE_UTILITY_UPGRADE = upgrade(
  'Free Utility Upgrade',
  BASE_FREE_UTILITY_UPGRADE_MIN,
  BASE_FREE_UTILITY_UPGRADE_MAX,
  BASE_FREE_UTILITY_UPGRADE_QUANTITY,
  BASE_FREE_UTILITY_UPGRADE_COST,
);

export const BASE_INTEREST_MIN = 0;
export const BASE_INTEREST_MAX = 5.94;
export const BASE_INTEREST_QUANTITY = 99;
export const BASE_INTEREST_COST = 7.36 * M;
export const INTEREST = upgrade(
  'Interest / Wave',
  BASE_INTEREST_MIN,
  BASE_INTEREST_MAX,
  BASE_INTEREST_QUANTITY,
  BASE_INTEREST_COST,
);

export const BASE_RECOVERY_PACKAGE_AMOUNT_MIN = 14;
export const BASE_RECOVERY_PACKAGE_AMOUNT_MAX = 38;
export const BASE_RECOVERY_PACKAGE_AMOUNT_QUANTITY = 60;
export const BASE_RECOVERY_PACKAGE_AMOUNT_COST = 321.28 * M;
export const RECOVERY_PACKAGE_AMOUNT = upgrade(
  'Recovery Amount',
  BASE_RECOVERY_PACKAGE_AMOUNT_MIN,
  BASE_RECOVERY_PACKAGE_AMOUNT_MAX,
  BASE_RECOVERY_PACKAGE_AMOUNT_QUANTITY,
  BASE_RECOVERY_PACKAGE_AMOUNT_COST,
);

export const BASE_RECOVERY_PACKAGE_MAX_MIN = 1.5;
export const BASE_RECOVERY_PACKAGE_MAX_MAX = 3;
export const BASE_RECOVERY_PACKAGE_MAX_QUANTITY = 50;
export const BASE_RECOVERY_PACKAGE_MAX_COST = 130.57 * M;
export const RECOVERY_PACKAGE_MAX = upgrade(
  'Max Recovery',
  BASE_RECOVERY_PACKAGE_MAX_MIN,
  BASE_RECOVERY_PACKAGE_MAX_MAX,
  BASE_RECOVERY_PACKAGE_MAX_QUANTITY,
  BASE_RECOVERY_PACKAGE_MAX_COST,
);

export const BASE_RECOVERY_PACKAGE_CHANCE_MIN = 6;
export const BASE_RECOVERY_PACKAGE_CHANCE_MAX = 30;
export const BASE_RECOVERY_PACKAGE_CHANCE_QUANTITY = 60;
export const BASE_RECOVERY_PACKAGE_CHANCE_COST = 321.28 * M;
export const RECOVERY_PACKAGE_CHANCE = upgrade(
  'Package Chance',
  BASE_RECOVERY_PACKAGE_CHANCE_MIN,
  BASE_RECOVERY_PACKAGE_CHANCE_MAX,
  BASE_RECOVERY_PACKAGE_CHANCE_QUANTITY,
  BASE_RECOVERY_PACKAGE_CHANCE_COST,
);

export const BASE_ENEMY_ATTACK_LEVEL_SKIP_MIN = 0.05;
export const BASE_ENEMY_ATTACK_LEVEL_SKIP_MAX = 35;
export const BASE_ENEMY_ATTACK_LEVEL_SKIP_QUANTITY = 699;
export const BASE_ENEMY_ATTACK_LEVEL_SKIP_COST = 123.43 * QUINT;
export const ENEMY_ATTACK_LEVEL_SKIP = upgrade(
  'Enemy ATTACK Level Skip',
  BASE_ENEMY_ATTACK_LEVEL_SKIP_MIN,
  BASE_ENEMY_ATTACK_LEVEL_SKIP_MAX,
  BASE_ENEMY_ATTACK_LEVEL_SKIP_QUANTITY,
  BASE_ENEMY_ATTACK_LEVEL_SKIP_COST,
);

export const BASE_ENEMY_HEALTH_LEVEL_SKIP_MIN = 0.05;
export const BASE_ENEMY_HEALTH_LEVEL_SKIP_MAX = 35;
export const BASE_ENEMY_HEALTH_LEVEL_SKIP_QUANTITY = 699;
export const BASE_ENEMY_HEALTH_LEVEL_SKIP_COST = 123.43 * QUINT;
export const ENEMY_HEALTH_LEVEL_SKIP = upgrade(
  'Enemy Health Level Skip',
  BASE_ENEMY_HEALTH_LEVEL_SKIP_MIN,
  BASE_ENEMY_HEALTH_LEVEL_SKIP_MAX,
  BASE_ENEMY_HEALTH_LEVEL_SKIP_QUANTITY,
  BASE_ENEMY_HEALTH_LEVEL_SKIP_COST,
);

export const UTILITY_UPGRADES = Object.freeze({
  [CASH_BONUS.name]: CASH_BONUS,
  [CASH_PER_WAVE.name]: CASH_PER_WAVE,
  [COINS_PER_KILL.name]: COINS_PER_KILL,
  [COINS_PER_WAVE.name]: COINS_PER_WAVE,
  [FREE_ATTACK_UPGRADE.name]: FREE_ATTACK_UPGRADE,
  [FREE_DEFENSE_UPGRADE.name]: FREE_DEFENSE_UPGRADE,
  [FREE_UTILITY_UPGRADE.name]: FREE_UTILITY_UPGRADE,
  [INTEREST.name]: INTEREST,
  [RECOVERY_PACKAGE_AMOUNT.name]: RECOVERY_PACKAGE_AMOUNT,
  [RECOVERY_PACKAGE_MAX.name]: RECOVERY_PACKAGE_MAX,
  [RECOVERY_PACKAGE_CHANCE.name]: RECOVERY_PACKAGE_CHANCE,
  [ENEMY_ATTACK_LEVEL_SKIP.name]: ENEMY_ATTACK_LEVEL_SKIP,
  [ENEMY_HEALTH_LEVEL_SKIP.name]: ENEMY_HEALTH_LEVEL_SKIP,
});

export const WORKSHOP_UPGRADES = Object.freeze({
  ...ATTACK_UPGRADES,
  ...DEFENSE_UPGRADES,
  ...UTILITY_UPGRADES,
});
